export const SIGNUP_REQUEST = 'LOGIN_USER';
export const SIGNUP_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_USER';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const GET_PARCELS = 'GET_PARCELS';
export const GET_PARCELS_SUCCESS = 'GET_PARCELS_SUCCESS';
export const GET_ONE_PARCELS = 'GET_ONE_PARCELS';
export const GET_ONE_PARCELS_SUCCESS = 'GET_ONE_PARCELS_SUCCESS';
