export const SIGNUP_USER = 'SIGNUP_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const GET_PARCELS = 'GET_PARCELS';
export const GET_PARCELS_SUCCESS = 'GET_PARCELS_SUCCESS';
export const GET_ONE_PARCELS = 'GET_ONE_PARCELS';
export const GET_ONE_PARCELS_SUCCESS = 'GET_ONE_PARCELS_SUCCESS';
